pb33f/libopenapi

document_test.go

No release required, no changes

Fixed document test

---

what-changed/model/schema.go

Schema properties were not being correctly checked, as validated when using the models to render a UI.

fix: Fixed inaccurate property checks on schemas for what-changed

---

datamodel/high/v3/document_test.go
datamodel/low/v3/create_document_test.go
index/spec_index.go
index/spec_index_test.go
resolver/resolver.go
resolver/resolver_test.go
test_specs/mixedref-burgershop.openapi.yaml
test_specs/single-definition.yaml
utils/utils.go
utils/utils_test.go

Poly references are now mapped, and path lookups are much more sensitive to crazy paths.

Updating resolving and path generation code

---

what-changed/model/comparison_functions.go
what-changed/model/comparison_functions_test.go
what-changed/model/example.go
what-changed/model/example_test.go

Fixes https://github.com/pb33f/libopenapi/issues/61

Fix what changed panic

---

datamodel/low/extraction_functions.go

@daveshanley I found a bug where in an array of parameters (example below) if the array had some references and some not then the values in the array without references were being set to the last found reference which came from the previous value in the array.
I fixed this for the use case I found, but not sure if you want to have a look over this to see if there is anywhere else this behavior might happen.
would also appreciate help putting together a test for this fix, in my rush I couldn't get my head around the best way to write a test for this.
here is the example that this fixes:
```yaml
parameters:
- $ref: "#/components/parameters/filterStart"
- $ref: "#/components/parameters/filterLimit"
- $ref: "#/components/parameters/filterEnd"
- $ref: "#/components/parameters/filterDirection" …
```

fix: for low model reference values in arrays being set incorrectly

---

datamodel/spec_info.go
document.go
utils/utils.go

just cleaning things up, preparing for online demo push for https://pb33f.io

A few tiny non breaking changes.

---

datamodel/document_config.go
datamodel/low/v3/create_document.go
document.go

Provide BasePath in the config to override CWD in the case when the app and the spec is in different folders

Fix local file resolve

---

datamodel/low/model_builder.go
datamodel/low/v3/path_item.go
datamodel/low/v3/paths.go

Fix Digital Ocean resolving (invalid spec)
Fix valid specs resolving

Fix multi file resolving

---

what-changed/model/schema.go
what-changed/model/schema_test.go

Keys were being compared incorrectly due to a combination of a swapped property, that sorts differently.

Fixed schema comparison for out of order keys. #170

---

index/resolver.go
index/resolver_test.go

Added back in logic required by vacuum.

---

datamodel/low/v2/swagger.go
datamodel/low/v3/create_document.go
document.go
index/resolver.go
index/rolodex.go
index/rolodex_test.go

Testing inside vacuum is throwing up a couple of small glicthes that need adding/tuning

Adding convenience methods and glitch fixes for 0.13

---

index/extract_refs.go
index/index_model.go
index/resolver.go
index/resolver_test.go

Resolving and indexing has changed, new code is required and this isue highlighted a glitch introduced with the addition of the rolodex when resolving.

v0.13.8: Addressed issue #195

---

datamodel/low/extraction_functions.go
datamodel/low/v3/paths.go
what-changed/model/paths.go

someone caused a panic, exposed an untested bug.

A few small bugfixes discovered from online users of openapi-changes

---

index/extract_refs.go

mentioned in https://github.com/daveshanley/vacuum/issues/400
No new features. There are no changes in here other than adding of a single if statement to check the length won't overflow. The diff looks nuts, but it's just formatting.

Added safety check for extracting refs from non-openapi files

---

datamodel/high/node_builder.go
datamodel/high/node_builder_test.go
index/spec_index_test.go

float without precisions are being rendered as
`!!float <your_number_here>`

float format to not print !!float

---

utils/utils.go
utils/utils_test.go

Was causing vacuum to crash during testing.

Added a nil check to lookup.

---

datamodel/high/base/schema_proxy.go

the logic has shifted around a little, no impact to experience, no breaking changes - but it does fix a few issues discovered by `libopenapi-validator`

slight modification to schema proxy

---

what-changed/model/schema.go
what-changed/model/schema_test.go

The property counts were off causing a deadlock.

Fixed locking issue

---

datamodel/high/node_builder.go
datamodel/high/node_builder_test.go
datamodel/high/v3/document_test.go
document_test.go

Fixes: https://github.com/pb33f/libopenapi/issues/376
Open question:
- Was the greater than zero check done to exclude the default value? I have made that assumption hence I have changed the condition to value != 0

fix error on negative float and int numbers

---

what-changed/model/schema.go

Swapped out custom counting code and channels for some good old fashioned wait groups.

fixed race condition in what-changed module

---

datamodel/low/base/xml.go
datamodel/low/base/xml_test.go
what-changed/model/schema.go
what-changed/model/schema_test.go

fixed a couple of glitches on the XML model.

---

datamodel/low/base/schema.go
datamodel/low/base/schema_test.go

stop a panic when hash is called on a nil pointer.

---

what-changed/what_changed_test.go

I'm working through a bug that manifested between  v0.21.12 and  v0.23.0 (noticed in openapi-changes v0.0.81).
Basically, if there is any self reference in a schema, the tool always reports no changes. Maybe self reference is bad? But this is an incorrect failure mode either way. I suspect they should work because they used to.

Add a failing test with self reference

---

datamodel/high/base/schema_proxy.go
datamodel/high/base/schema_proxy_test.go

fixes #453
This is also cooking doctor https://github.com/pb33f/doctor/issues/67

Fix Race Condition in Doctor + Other Usages with Cache Usage

---

datamodel/constants.go
datamodel/high/v3/path_item.go
datamodel/high/v3/path_item_query_test.go
datamodel/low/v3/path_item.go
datamodel/low/v3/path_item_query_test.go
datamodel/schemas/oas32-schema.json
datamodel/spec_info.go
datamodel/spec_info_test.go
datamodel/translate_coverage_test.go
index/index_model.go
index/spec_index.go
what-changed/model/path_item.go
what-changed/model/path_item_query_test.go

model and what-changed now support OpenAPI 3.2 QUERY operations.

Added 3.2 support for QUERY operation.

---

datamodel/high/base/schema.go
datamodel/high/base/schema_proxy.go
datamodel/high/node_builder.go

all errors were being dropped and this was causing issues downstream.

Add error handling to node builder.
