pb33f/libopenapi

datamodel/high/base/schema_proxy.go
datamodel/high/base/schema_test.go

A client of high-level SchemaProxy may want to know whether a schema is a reference and the name of the reference.  This information is available from methods GetSchemaReference() and IsSchemaReference() in low-level SchemaProxy.  Provide a GoLow() method to retrieve the low-level SchemaProxy for a high-level SchemaProxy.

Add GoLow method to high-level SchemaProxy

---

datamodel/high/base/info.go
datamodel/high/base/info_test.go
datamodel/low/base/info.go
datamodel/low/base/info_test.go

From the [Open API 3.1 spec](https://spec.openapis.org/oas/latest.html#info-object) on the top-level `info` object:
> This object MAY be extended with [Specification Extensions](https://spec.openapis.org/oas/latest.html#specificationExtensions).
This PR implements support for that, which is relevant for supporting [Restish Open API extensions](https://rest.sh/#/openapi?id=name) which let you e.g. modify the name, description, etc or hide operations from the CLI directly from your Open API spec.
I added a basic test which covers the newly added lines. I see the Go formatter changed a couple of things - let me know if that's a problem and I'll undo those changes.
Part of https://github.com/danielgtaylor/restish/issues/115

feat: add extensions to info

---

document_test.go
index/spec_index.go
index/spec_index_test.go

When paths are wrapped in an array, the index throws an error because it's expecting them to be supplied as a map. Now paths can be wrapped or unwrapped, the index won't care.

fix: panic thrown when paths is wrapped in an array #4

---

datamodel/high/base/schema.go
index/spec_index_test.go

Multiple polymorphic, deeply embedded schemas cause resolving issues as a channel waits forever due to a counting issue.
This has been resolved.
Signed-off-by: Dave Shanley <dshanley@splunk.com>

Fixed resolving bug with polymorphic schemas.

---

datamodel/high/base/schema.go
datamodel/high/base/schema_test.go

It looks like the high level schema `Minimum`, `Maximum`, and `MulitpleOf` would always get set to `int64(0)` which, unfortunately, is a valid value and should be differentiated from "not present". This PR fixes it so that they are set conditionally and only when present in the incoming YAML. I need this to render accurate terminal-friendly schemas for input/output models in Restish help documentation.
I also added some tests for these cases and fixed a couple of examples where the incorrect YAML node was passed in.
I'm not sure how these fields are getting used/checked by https://github.com/daveshanley/vacuum so you might want to double check I didn't break anything there with this change :smile:
Part of https://github.com/danielgtaylor/restish/issues/115

fix: conditionally set min/max/multiple

---

datamodel/high/base/schema.go
datamodel/high/base/schema_test.go

It looks like the `schema.Examples` field was missed when loading the high-level schema from a low-level one. This adds it along with a test. It allocates a new slice because we want to go from the low-level model to just the values in a `[]any`.
Part of https://github.com/danielgtaylor/restish/issues/115

fix(high): load schema.Examples into []any

---

datamodel/high/v3/document.go
datamodel/high/v3/document_test.go
datamodel/high/v3/server.go
datamodel/low/v3/media_type.go
datamodel/low/v3/server.go
what-changed/model/example_test.go
what-changed/model/media_type.go
what-changed/model/media_type_test.go
what-changed/model/operation.go
what-changed/model/operation_test.go
what-changed/model/response.go

This release fixes a couple of missing elements:
- The v3 high-level `Document` object was incorrectly implemented. The `security` property needed to be a slice. **Breaking**
- `Server` was missing extensions in both high and low-level APIs.
This is a whole feature bump because of the change to the `Document` model. `Security` is now a slice and not a single instance. A small breaking change, but a breaking one none-the-less

Version 0.3.0

---

datamodel/spec_info.go
datamodel/spec_info_test.go
document.go

The issue lay with the `ExtractSpecInfo()` method from within the `datamodel` module. There is a round of parsing that happens in another thread inside there, and a notification is pumped down a channel once done. The problem is that nothing was listening on that channel, so everything in those threads just kept piling up with the garbage collector unable to free any of it.

(fix): A memory leak was detected and fixed #46

---

index/spec_index.go
index/spec_index_test.go

This attempts to improve the completion of the index.Reference types when dealing with parameters so the path is available for rules in vacuum to use, as it is quite hard otherwise to determine the index of a parameter for a json path when using the index
The Official Go extension for VSCode reformatted the code, let me know if you want the formatting reverted

feat: add path to references and parameters

---

index/spec_index.go
index/spec_index_test.go

This adds paths and parent nodes to the references for servers which help to improve any code using these references

feat: add parent nodes and paths to server index references

---

datamodel/low/v3/components.go

Security schemes with a `X-` prefix were being seen mistakenly as extensions, because the key name was automatically set to lowercase, before a check.

(fix): `X-` is a valid prefix for `SecurityScheme` components. #54

---

datamodel/spec_info.go
datamodel/spec_info_test.go

This fixes setting the correct JSON schema for OAS 3.1 documents. It was set to the default 3.0.

Fix setting JSON schema for OAS 3.1.0

---

README.md
index/spec_index.go
index/spec_index_test.go

Local files expected a component path (#/something/) to be postponed to the URL. This fix allows full file imports now to be supported in-line.
This was reported in https://github.com/daveshanley/vacuum/issues/225, and it's a continuation of the issue found in https://github.com/pb33f/libopenapi/issues/37. This fix allows the full import of the file (not just a path/component) to be imported.
Signed-off-by: Dave Shanley <dave@quobix.com>

fix: Index incorrectly handling file references 

---

what-changed/model/change_types.go
what-changed/model/comparison_functions.go
what-changed/model/document_test.go
what-changed/model/example.go

Examples can be anything, most commonly maps. Previously `libopenapi` did not check maps correctly. Now it does. It was also creating a panic by inserting a nil pointer as the value to a map key. This has also been fixed.
Examples are the only element that uses this pattern for comparison.

fix: Handle example comparison correctly. #61

---

datamodel/high/v3/document_test.go
datamodel/low/base/schema_test.go
datamodel/low/extraction_functions_test.go
datamodel/low/reference_test.go
datamodel/low/v3/create_document_test.go
datamodel/low/v3/paths_test.go
document_test.go
index/circular_reference_result.go
index/spec_index.go
resolver/resolver.go
resolver/resolver_test.go
test_specs/circular-tests.yaml
test_specs/swagger-circular-tests.yaml
test_specs/swagger-invalid-recursive-model.yaml
test_specs/swagger-valid-recursive-model.yaml
utils/utils.go

This PR contains an initial fix for pb33f/libopenapi#49.
It adds the following features to the library:
* `index.CircularReferenceResult.IsInfiniteLoop` - Set to true if each definition in the journey is marked as required
* `index.Reference.RequiredRefProperties` - Contains a map of definition references to the property name(s) which use it
`resolver.Resolver.CheckForCircularReferences()` and `resolver.Resolver.Resolve()` now check for `circRef.IsInfiniteLoop` when iterating through `resolver.Resolver.circularReferences`. If the value is `false`, then this is now accepted and no error is added to `resolver.Resolver.resolvingErrors`, as optional items within circular references allow a termination point, thus it's a valid spec.
I noticed whilst reading through the code that it will …

feat: Allow circular references which contain optional properties in their journeys

---

datamodel/low/base/schema.go
datamodel/low/base/schema_proxy.go
document_test.go
test_specs/ref-followed.yaml

If schemas item is a `$ref` then it wasn't parsed using BuildModel.
This PR moves BuildModel to lo schema.Build and works on possible dereferenced root yaml node.

Fix ref object parsing

---

datamodel/low/v3/paths.go
document.go

No breaking changes, errors and model are returned now (allows errors and model through). And a small fix to the paths hashing mechanism to ensure identical paths with different names are checked.

Couple of small fixes for what-changed.

---

datamodel/high/v3/operation.go
datamodel/high/v3/operation_test.go

addresses https://github.com/pb33f/libopenapi/issues/70

fix: callbacks not being populated in high model

---

datamodel/high/base/schema.go
datamodel/high/base/schema_test.go

Found a small issue while upgrading to the latest libopenapi. The new `DynamicValue.N` field is not copied over from the low-level model, so for example `schema.ExclusiveMinimum.IsB()` will *always* return `false`. This PR fixes it and adds a small test to assert the values get set. For the boolean case it is left alone as `N` will default to zero.
Note: this is important as the exclusive minimum can be zero, in which case it's currently not possible to determine whether a value was set or which one was set.
Sorry for the delay in upgrading BTW, I got side-tracked shipping https://rest.sh/#/bulk

fix: DynamicValue in high model schema missing N value

---

datamodel/low/extraction_functions.go
document.go
index/spec_index.go
index/spec_index_test.go
resolver/resolver.go

There is new code that looks for inline `schema` definitions and collects them, as well as a further subset of references that are precisely `object` or `array` types. 
The `index.GetAllSchemas()` method now returns a slice of *Reference pointers, rather than a map of them. The original behavior of `GetAllSchemas()` has been replaced with `GetAllComponentSchemas()` which retains the signature.
Two new additional methods `GetAllInlineSchemas()` and `GetAllInlineSchemaObjects()`. The former will return everything in the spec marked with `schema` that is not a reference. The latter will return everything the former does, except filtered down by `object` or `array` types.
Also, the index is now bubbled up through the document model. There isn't a simple way to get access to it. A small non …

feat: Add index for getting all "schema" objects #50 (Breaking Change)

---

index/spec_index.go

a small oversight in 0.5.0 means that using a `schema` anywhere other than a label, caused the index to get upset. This has now been resolved.

fix: panic when `schema` used as non-label #76

---

datamodel/low/v3/create_document.go
index/extract_refs.go
index/find_component.go
index/index_model.go
index/spec_index.go
index/spec_index_test.go
index/utility_methods.go
index/utility_methods_test.go

The index runs async everywhere, it's kind of impossible to know which path with resolve first, so testing is hard. Sometimes a race condition is hit. Well, it was. Now that map has a mutex on it.
Also fully fixed handling files with relative links. A basepath property has been added to the index configuration to allow a local root to be set when resolving files.
Added a full checkout test for the digital ocean spec so that complete remote and full local testing is performed.

Fixed async issues with index #91

---

datamodel/high/base/info.go
datamodel/high/base/info_test.go
datamodel/low/base/info.go
datamodel/low/base/info_test.go
what-changed/model/info.go

This adds the missing Summary attribute to the doc.Info object for 3.X specs, this isn't present for OpenAPI 2 specs which means that it will always be empty but I think that is okay and avoided the need to have a v2 and v3 version of this object.
Also the TestSpecIndex_SearchIndexForReference_ExternalSpecs test was failing which I believe is unrelated to this change and it failed non-deterministically sometimes timing out all together

fix: add missing summary for OpenAPI 3.X docs

---

datamodel/high/base/schema.go
datamodel/high/base/schema_test.go
datamodel/high/node_builder.go
datamodel/high/node_builder_test.go
datamodel/low/base/schema.go
datamodel/low/base/schema_test.go
datamodel/low/model_builder.go
datamodel/low/model_builder_test.go
datamodel/schemas/oas3-schema.json
datamodel/schemas/oas31-schema.json
datamodel/spec_info_test.go
document_examples_test.go
utils/utils.go
utils/utils_test.go

UniqueValues was marked as an integer, not a boolean. Some other tweaks and tunes after cleaning up vacuum.
Numbers and integers are now correctly handled with some places. A number of primitives were being rendered back out as strings, which when read back in down stream, was causing some validation issues.

Updated embedded OAS schemas and fixed UniqueValues

---

index/extract_refs.go
index/find_component.go
index/find_component_test.go
index/index_model.go
index/search_index.go
index/search_index_test.go
index/spec_index.go
index/spec_index_test.go
resolver/resolver_test.go
test_specs/first.yaml
test_specs/second.yaml
test_specs/third.yaml
utils/utils.go

In vacuum, a usecase was reported where an infinite loop occurred due to re-parsing the same reference over and over in a loop. It was re-creatable and it was because the loop happened before the index was ready.
This should be resolved now, at least for this use case. To be sure, I have included the specs as a new test.
No new features except some properties added to configuration structs.
https://github.com/daveshanley/vacuum/issues/268

Fix for resolving looping relative references v0.8.2

---

.gitignore
index/spec_index.go
index/spec_index_test.go

also adds a `.gitignore` file as there was a `test-operation.yaml` file created when running the tests locally

fix: add missing path and parent node to paths index references

---

datamodel/low/extraction_functions.go
utils/utils.go

On very large specs `ToLower` becomes a bottleneck since it reallocates a lot

Use EqualFold ti avoid memory reallocations

---

datamodel/high/base/schema.go
what-changed/model/comparison_functions.go

Found race conditions in `comparison_functions.go` and `high/base/schema.go`. 
* Removed asynchronous nature of `buildProps()` in `NewSchema()`
* In `CheckMapForChangesWithComp()` the lock now covers writes `p[k].GetValueNode().Value = k` when they occur.

Fix race condition in Schema & Comparisons 

---

datamodel/high/base/schema.go

`unevaluatedProperties` was not being handled correctly by the high-level v3 schema. When being rendered down for validation, the correct type on the dynamic value was not being set correctly. This has been resolved without any change in coverage or needing new tests.

Fixed high-level model handling of `unevaluatedProperties` #145

---

datamodel/document_config.go
datamodel/spec_info.go
datamodel/spec_info_test.go
document.go
document_test.go

This allows vacuum to operate outside of the OpenAPI world. Exciting!
New `DocumentConfiguration` property added.
`BypassDocumentCheck` will bypass the document check. This is disabled by default. This will allow any document to
passed in and used. Should only be enabled when loading non OpenAPI docs.

Added general linting support for non openapi files.

---

index/find_component.go
index/find_component_test.go

path unescape url when resolving remote reference

---

datamodel/high/node_builder.go
go.sum

was blowing up with some invalid specs.

Added zerocheck for node builder

---

datamodel/high/base/schema.go
datamodel/low/base/schema.go
datamodel/low/base/schema_test.go
datamodel/low/v3/constants.go
what-changed/model/schema.go

Libopenapi was missing the ability to access the [const field](https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values) of a schema.
This adds that

fix: add missing const value to schema

---

index/extract_refs.go
index/extract_refs_test.go

An edge case reported in https://github.com/daveshanley/vacuum/issues/339 shows up when enums are being indexed when they are actually a property of a schema called ‘enum’.
This has been fixed.

Properties named ‘enum’ were being indexed as enums

---

datamodel/high/base/schema.go
datamodel/high/base/schema_proxy.go
datamodel/high/base/schema_test.go

Rendering causes bits to be set on structs in the model. Concurrency causes race issues with reading a writing of these bits, as there is no locking in the model.
Until now. locking prevents concurrent renders that use a shared model from conflicting with one another.
Addresses #163 and https://github.com/pb33f/libopenapi-validator/issues/23

Added `SchemaProxy` mutex #163

---

datamodel/high/v2/swagger_test.go
datamodel/high/v3/media_type_test.go
datamodel/high/v3/package_test.go
datamodel/low/v2/package_test.go
datamodel/low/v2/swagger_test.go
datamodel/low/v3/examples_test.go
datamodel/spec_info_test.go
index/spec_index_test.go
what-changed/reports/summary_test.go
what-changed/what_changed_test.go

There are no functional changes because ioutil.ReadFile and ioutil.WriteFile simply call os.ReadFile and os.WriteFile respectively.

chore: replace use of deprecated ioutil with os

---

renderer/schema_renderer.go

Simplify code by taking the first element instead of performing a single-iteration loop.
Disclaimer: I wasn't actually 100% sure if there was some magic going on that I didn't realize.
Discovered using https://github.com/golangci/golangci-lint

refactor: remove single iteration loop

---

what-changed/model/info.go
what-changed/model/info_test.go

This commit provides a fix for issue #184

fix: introduce extension change detection for info section

---

utils/utils.go
utils/utils_test.go

Also reduce execution time of ConvertComponentIdIntoFriendlyPathSearch by 50-60% and add benchmark
Lint issues fixed:
```
utils/utils.go:567:22: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
var bracketNameExp = regexp.MustCompile("^(\\w+)\\[(\\w+)\\]$")
^
utils/utils_test.go:232:28: S1040: type assertion to the same type: parsed already has type interface{} (gosimple)
assert.Equal(t, "niblet", parsed.(interface{}))
^
utils/utils_test.go:171:2: S1021: should merge variable declaration with assignment on next line (gosimple)
var d interface{}
^
utils/utils_test.go:198:2: S1021: should merge variable declaration with assignment on next line (gosimple)
var d interface{}
^
utils/utils_test.go:236:2: S1021: should merge variable …
```

Fix lint issues in util

---

datamodel/document_config.go

vacuum needs the ability to enable remote lookups without providng a baseURL, so the same should apply for files.  undeprecating this so vacuum’s pipeline does not complain about deprecated functions.

Un-deprecated some flags we still need.

---

utils/utils.go
utils/utils_test.go

Reported by vacuum issue, this use-case is now handled correctly and prevents a panic.

Off by one issue fixed https://github.com/daveshanley/vacuum/issues/356

---

index/resolver.go
index/resolver_test.go
index/spec_index_test.go

If the number of relatives exceeds 500  deep when resolving, libopenapi will now log a warning and escape that path from continuing. There is no reason on earth for a depth this large. It most likely indicates a circular reference that was ignored and then resolved.

Added a safety check to resolver

---

index/resolver.go
index/resolver_test.go

This builds on the last patch, by also catching the issue in the resolver and then allowing it to bubble up to applications. no new fixes, no new features, just better integration so vacuum can report the issues.

Catching circular references that spin out of control

---

index/rolodex_file_loader.go
index/rolodex_test.go
index/spec_index_test.go

I have seen this issue appear online a few times, the CPU locks at 100% when throwing a bad reference.
This happened because the local ‘lock’ used by the rolodex file loader, was not releasing correctly when a lookup occurred, that could not be found via a rolodex file lookup.
https://github.com/daveshanley/vacuum/issues/393

Fixed deadlock causing 100% CPU spike

---

datamodel/low/base/schema.go

Context was not being carried through correctly when resolving using `Schema()` and using exploded files.

Fixed glitch reported by #219

---

datamodel/low/v2/swagger_test.go
datamodel/low/v3/create_document.go
datamodel/spec_info.go
datamodel/spec_info_test.go
datamodel/translate_test.go

It does no good to anyone, anywhere and is creating race conditions when using the stack in a multi-tenant fashion.

Removed `JsonParsingChannel`

---

what-changed/model/comparison_functions.go
what-changed/model/schema_test.go

A fix for issue #231 
I have addressed the issue by implementing a simple fix: removing the encoding from the toString function. However, it became apparent that this alone was insufficient. The toString function is crucial when storing the node.Yaml enum object string value as a key in a map, which is used for comparison between the right and left sides. 
To mitigate this issue, I have modified the toString function to return the encoded string without including the column and line information. To prevent the loss of the original object's line and column data, I have utilized a copy of the object. This ensures that the comparison is not adversely affected by the line and column information, while still preserving the integrity of the original object's data.

Missing Line and Column Information in model.ChangeContext for Enum Changes fix

---

datamodel/low/v3/create_document.go
index/resolver.go

Vacuum runs things multiple times. which is causing skew on references.
No new features, but will resolve #229 (when consumed by vacuum)

Added switch to resolver for preventing duplication.

---

what-changed/model/operation.go
what-changed/model/operation_test.go
what-changed/model/path_item.go
what-changed/model/path_item_test.go

Optional parameters being added are not breaking, this was reported in openapi-changes. https://github.com/pb33f/openapi-changes/issues/87
If a parameter is added to a path item or an operation that is not required, then it is now not considered a breaking change.

Fixed issue with optional parameters when diffing

---

index/resolver.go
index/resolver_test.go
index/rolodex_test.go
index/spec_index_test.go

- Test case taken from [docs](https://pb33f.io/libopenapi/circular-references/#circular-reference-results)
- Applying fix for _TestResolver_CheckForCircularReferences_IgnorePoly_Any_ to pass
- Adjusting expectations for _TestRolodex_IndexCircularLookup_LookupHttpNoBaseURL_  because of **cf.IgnorePolymorphicCircularReferences = true**

Fix circular polymorfic ref

---

bundler/bundler.go
bundler/bundler_test.go

Exploded ref definition was matching against empty string, however full definition consists of [full path and a fragment](https://github.com/pb33f/libopenapi/blob/main/index/extract_refs.go#L219)
Fixes #238

[bundler] Add exploded ref check against root document

---

datamodel/low/base/schema.go
datamodel/low/base/schema_test.go
document_test.go
index/extract_refs.go
index/search_index.go
test_specs/nested_files/components/parameters/header/page-size.yaml
test_specs/nested_files/components/parameters/query/$select.yaml
test_specs/nested_files/components/requestBodies/AccountModel.yaml
test_specs/nested_files/components/responses/Unspecified200.yaml
test_specs/nested_files/components/schemas/AccountModel.yaml
test_specs/nested_files/openapi.yaml
test_specs/nested_files/paths/v1_Accounts.yaml

Building out a model, the current position was getting a bit muddled with deeply nested file references.

Fixed issue reported in discord channel

---

utils/utils.go

bumping timeout in lieu of this feature https://github.com/pb33f/libopenapi/issues/251

chore: bump timeout on FindNodesWithoutDeserializing

---

bundler/bundler.go
bundler/bundler_test.go

in some cases, `BuildV3Model` will return a nil first parameter and an error which result in a panic in the next call, this PR aims to fix this behavior.

fix bundler panic when BuildV3Model fail

---

datamodel/low/v3/media_type.go
datamodel/low/v3/request_body_test.go

@daveshanley this fixes an issue where the `MediaType.Example` field was being populated when it shouldn't.
It was basically searching down into the schema and other places as well to find an example where it should have only been searching the top level node

fix: fixed MediaType example being populated from wrong source

---

utils/utils.go

Adds length check to prevent a panic if a $ref is mis-used.

Fix panic when ref is mis-used

---

index/extract_refs.go
index/spec_index_test.go

fixes https://github.com/pb33f/libopenapi/issues/280

fix: issue-280 Index.GetAllSchemas() regression in values returned

---

index/spec_index_test.go

I wanted to open a PR for something else, but the tests were failing.
The digital ocean API repo does not change often, but when it does it likely breaks the tests here.
I'd suggest to pin a certain commit.
If you want, I can also de-duplicate the checkout code between the tests, but it looks like the tests were explicit on purpose

Pin digital ocean commit in tests

---

document.go
document_test.go

~~(unrelated tests are currently failing, fixed in #287 )~~ ✅ 
The error handling for `newDoc.BuildV3Model()` was wrong and the error was not properly propagated. The provided test only runs successful with the change.

Fix RenderAndReload error handling

---

datamodel/high/node_builder.go
datamodel/high/v3/oauth_flow.go
orderedmap/builder.go

see https://github.com/pb33f/libopenapi/issues/289
This is my naive attempt to fix the issue.  It works but it may have negative side-effects I'm not aware of.

render empty oauth scopes

---

index/spec_index_test.go

This PR addresses a failing test caused by changes in the upstream repository [`digitalocean/openapi`](https://github.com/digitalocean/openapi/pull/878). The test depended on the number of files in the `specification` directory, causing it to break whenever files were added or removed. This fix pins the DigitalOcean spec index test to a specific commit hash to ensure consistent test results.
- **Stability**: Tests will no longer break due to changes in the number of files in the upstream repository.
- **Reliability**: Ensures consistent and predictable test outcomes.

Pin DigitalOcean spec index test to a specific commit hash

---

datamodel/low/extraction_functions_test.go
document_iteration_test.go
go.mod
go.sum
index/extract_refs.go
index/index_model.go
index/resolver.go
index/rolodex_file_loader.go
index/rolodex_remote_loader.go
index/spec_index.go
index/spec_index_test.go
renderer/schema_renderer.go
what-changed/model/schema.go

removed golang.org/ x package in favour of the std lib

removed golang x package in favour of the std lib

---

datamodel/high/node_builder.go
datamodel/high/v3/document_test.go
test_specs/nullable-examples.openapi.yaml
utils/nodes.go
utils/nodes_test.go

Fixes https://github.com/pb33f/libopenapi/issues/301.
TL;DR go-yaml currently panics when trying to render the test case. So we've got to short-circuit the "empty node" to not use `Encode` to copy across the empty scalar node, but just set the value explicitly

fix: render empty scalar nodes

---

datamodel/high/v3/media_type_test.go
datamodel/high/v3/parameter_test.go
datamodel/low/v3/media_type.go
datamodel/low/v3/media_type_test.go
datamodel/low/v3/parameter.go
datamodel/low/v3/parameter_test.go

This fixes an issues where the schema level examples were wrongly being extracted and didn't properly match the shape of the top level named examples.
This PR ensures only the right examples are extracted

fix: fixed extraction of top level named examples to not extract schema level examples

---

json/json.go
json/json_test.go

Makes it possible to render yaml that uses anchors and complex map keys

fix: improved handling of complex yaml in YAMLNodeToJSON

---

datamodel/high/v3/components.go
datamodel/high/v3/components_test.go
datamodel/low/v3/components.go
datamodel/low/v3/components_test.go
datamodel/low/v3/constants.go

I don’t know how I missed this.
I don’t know how someone has not complained about it.

added `pathItems` to components.

---

bundler/bundler_test.go
datamodel/document_config.go
datamodel/low/v3/create_document.go
index/index_model.go
index/rolodex.go
index/rolodex_test.go
index/search_index.go
index/spec_index.go

Instead of using "root.yaml" as a theoretical root, use the real filename of the root spec (often openapi.yaml). This fixes issues with resolving references in rules such as unused-components.

Use real root filename as theoretical root yaml file

---

datamodel/high/v3/server_variable.go
datamodel/high/v3/server_variable_test.go
datamodel/low/v3/server.go
datamodel/low/v3/server_test.go
datamodel/low/v3/server_variable.go

Allow to use server variable extension:
```
envVar := &v3.ServerVariable{
Enum:       []string{"api.mycompany.com", "api-preprod.mycompany.com"},
Extensions: orderedmap.New[string, *yaml.Node](),
}
envVar.Description = "Environment to use"
envVar.Default = "api.mycompany.com"
envTransforms := []map[string]interface{}{
{
"type": "translate",
"translations": []map[string]string{
{"from": "prod", "to": "api.mycompany.com"},
{"from": "pre-prod", "to": "api-preprod.mycompany.com"},
},
},
}
envVar.Extensions.Set("x-transforms", createExtension(envTransforms))
server.Variables.Set("env", envVar)
mergedSpecA.Model.Servers = append(mergedSpecA.Model.Servers, server)
```

feat: add server variable extensions

---

datamodel/low/base/context.go

No fixes or features, just an import update to fix a downstream build problem.

v0.18.2 import for context was wrong.

---

index/extract_refs.go
index/rolodex_test.go
index/rolodex_test_data/components.yaml
index/rolodex_test_data/paths/paths.yaml
index/search_rolodex_test.go
index/utility_methods.go

This fixes vacuum rules that lookup operations in the index where:
1. The original spec (root.yaml) has an external reference to a file in a different directory `./paths/mypath.yaml`
2. In that location, there is a relative reference to a path-item in a nearby file, e.g. `./components.yaml#/path-item`
What was previously happening in [2] is that the `./components.yaml` was being resolved in `./components.yaml` (the parent directory) instead of `./paths/components.yaml` (the right directory). This resulted in a failure to evaluate path item references and unexpected linting failures. 
This changes adjusts the lookup to search through the index's nodeMap to find the location of the YAML `$ref` node value that's been evaluated.  Once we find it, we lookup the associated index of that file …

fix: a parameter in the rolodex should be evaluated using the index that the node is in

---

index/utility_methods.go
index/utility_methods_test.go

Added in 713aeecdfa, appears to have never been used.

chore: remove unused param from extractRequiredReferenceProperties

---

index/rolodex_test.go
index/rolodex_test_data/doc1.yaml
index/rolodex_test_data/operations.yaml
index/spec_index.go

**Why**
We have a linting rule which checks for duplicate operation IDs / duplicate operations. This linting rule wasn't catching duplicates if the operations were living in an external $ref.
**What**
Currently when building the index of operations we weren't checking for refs, this PR changes that.

fix: indexing of operations which are `$ref`s

---

datamodel/high/base/schema_proxy.go
datamodel/low/base/schema_proxy.go
datamodel/low/base/schema_proxy_test.go
document_iteration_test.go
index/cache.go
index/cache_test.go
index/cache_test/docusign_test.go
index/index_model.go
index/rolodex.go
index/rolodex_test.go
index/spec_index_test.go

high memory use is a problem in libopenapi, this change moves us a step closer to fixing that. Very reference heavy specs can create an ungodly number of schema proxy calls when the model is being walked.
For example the docusign spec (which has been added to the test suite) creates 4m proxy calls. This is not required as it’s the same ref being called over and over and we already have it after it’s been done once. This change adds a high level cache to prevent the over production of schemas.

Added a high level cache.

---

index/index_model.go
index/spec_index.go
index/spec_index_test.go

- solves issue #333 
- Accessing GetAllComponentSchemas causes a race condition error during usage. 
- Adds a RWLock to ensure that the map object is safely created across go routines. This pattern is used for other similar fields

Add RW Lock to allComponentSchemas to Prevent Data Race Error

---

document.go
document_test.go

- Expanded the existing check during `Render` to generally check for a `nil` `highOpenAPI3Model`, with more specific error message depending on if it's Swagger or not.
- Also added a check for the `info` which is a pointer, so could _technically_ be `nil`.
- Added a test case to ensure we error. Without my changes the test panics which we're trying to avoid.
Context: I've previously hit a `panic` while learning about & implementing the library. It took me a while to figure out why and got me a bit spooked to have this in a long-running cluster/container. I added a `recover` in my end, but handling it here cleanly is nicer.

Add `nil` check on Document Render to avoid panic

---

bundler/bundler.go
bundler/bundler_test.go
datamodel/document_config.go
datamodel/low/extraction_functions.go
datamodel/low/extraction_functions_test.go
datamodel/low/v3/create_document.go
datamodel/low/v3/create_document_test.go
document.go
document_test.go
go.mod
go.sum
index/extract_refs.go
index/rolodex.go
index/rolodex_file_loader.go
index/rolodex_remote_loader.go
orderedmap/orderedmap_test.go
test_specs/minimal_remote_refs/openapi.yaml
test_specs/minimal_remote_refs/schemas/components.openapi.yaml

Thanks for working on all these tools for OpenAPI. 👏 
I've run into issues with vacuum/libopenapi supporting resolving of relative remote refs. I'm trying to fix this, but I have to admit I get completely lost in the code of this project.
I've added a test case to debug the issue. One thing I notice and that I think it should never happen, is that `libopenapi` tries to load a file that's not referenced anywhere. The log output says the following:
```
{"time":"2024-09-03T22:46:30.36193+02:00","level":"ERROR","msg":"unable to fetch remote document","file":"/felixjung/libopenapi/authed-remote/test_specs/schemas/components.openapi.yaml","status":404,"resp":"404: Not Found"}
{"time":"2024-09-03T22:46:30.362202+02:00","level":"ERROR","msg":"unable to locate reference anywhere in the …
```

Fix: resolve remote relative refs correctly

---

datamodel/spec_info.go

Update spec_info.go , handle version prefix

[fix] Support OAS 3.1X

---

what-changed/model/schema.go
what-changed/model/schema_test.go

Fix this issue 
https://github.com/pb33f/openapi-changes/issues/135

Fix enum comparison by looking on the definitive value (without style)

---

index/extract_refs.go
index/extract_refs_test.go
index/index_model.go
index/spec_index_test.go

extensions that contain references will not be parsed, they should not be parsed, unless you want them to, and then, well, so you can! 
Now comes with a configurable switch in the config.

Fixed issue with `$refs` being picked up in extensions.

---

README.md

Hi, 
I have utilized the `libopenapi` package to generate OpenAPI specifications in the [Gleece](https://github.com/gopher-fleece/gleece) project.
If you think this project meets your standards, I will be happy to be added to the dependent projects list. In any case, thank you for creating this awesome project!

Add Gleece to the list of projects depending on libopenapi.

---

index/cache.go
index/cache_test.go
index/find_component_test.go
index/index_model_test.go
index/rolodex_file_loader_test.go
index/rolodex_remote_loader_test.go
index/rolodex_test.go
index/spec_index.go
index/spec_index_test.go

This should address issue: #383
Remove initialisation side effect from `GetHighCache()`
- Pull initialisation of `index.highModelCache` out of `GetHighCache()` and create a new function `InitHighCache()`
- **For active code**, call that new function everywhere a `SpecIndex` is created. This ensures that the cache *is always* initialised and no longer requires the side effect in `GetHighCache()`
- **For unit tests** that also rely on that _side-effect_.
- Create a new unit-test helper `NewTestSpecIndex()` that initialises the high cache.
- Use that everywhere a new `SpecIndex` is created.

Fix: Address issue: #383

---

datamodel/high/base/schema_proxy.go

We are using `libopenapi` + `vacuum` for our internal tooling. We've run into data race in our unit tests:
```
==================
WARNING: DATA RACE
Write at 0x00c000520198 by goroutine 305:
github.com/pb33f/libopenapi/datamodel/high/base.(*SchemaProxy).Schema()
project/vendor/github.com/pb33f/libopenapi/datamodel/high/base/schema_proxy.go:146 +0xbb9
github.com/pb33f/doctor/model/high/base.(*SchemaProxy).Walk()
project/vendor/github.com/pb33f/doctor/model/high/base/schema_proxy.go:80 +0xfd
github.com/pb33f/doctor/model/high/v3.(*MediaType).Walk.func1()
project/vendor/github.com/pb33f/doctor/model/high/v3/media_type.go:39 +0x65
github.com/sourcegraph/conc/panics.(*Catcher).Try()
project/vendor/github.com/sourcegraph/conc/panics/panics.go:23 +0x77 …
```

fix: lock before checking sp.rendered to avoid datarace

---

datamodel/high/base/schema_proxy.go

During cache hits, parent proxy was stickily assigned to the original
schema. This was incorrect as a component can be referenced multiple
times in the same document.
We now assign the parent proxy to the cloned schema.

fix: attribute correct parent proxy to schemas

---

datamodel/high/base/schema_proxy.go

Fix a regression with my recent change #391 
If I were to create a SchemaProxy from `CreateSchemaProxy`, `Schema()` will return `nil`. I do this in unit tests. 
In reality though, `schema` should be present.
We should keep original logic where we check `rendered` first before checking if schema is nil. So we move the check for `schema` after `rendered` check like before. They are both in critical section to prevent datarace issue from before.

fix: check rendered first to fix a regression

---

renderer/schema_renderer.go
renderer/schema_renderer_test.go

Given a specification
```
type: [object]
required:
- drink
- missing
properties:
burger:
type: string
fries:
type: string
drink:
type: string
```
I expect a mock
```
{
"drink": "test",
"missing": {} // or any other value
}
```
Currently, it crashes due to dereferencing a nil pointer.
This PR proposes rendering the missing required property by setting it to an empty object; we could also set it to any other type (like string, integers, ...). I believe the OpenAPI specification allows any type if the property is missing in the `properties` field.
I am very new to Go. Let me know if I do something very weird.

Bug: Render missing required property 

---

renderer/schema_renderer.go
renderer/schema_renderer_test.go

This PR enhances the rendering of schemas containing circular references.
Previously, circular references caused excessively deep nesting, only terminating when the maximum depth limit was hit. This update introduces more intelligent handling to avoid that behavior.
Assume we are given this schema `S`
```
schemas:
human:
type: object
properties:
name:
type: string
example: John Doe
pets:  
type: array
items: 
$ref: "#/schemas/animal"
animal:
type: object
properties:
name:
type: string
example: Bob the cat
offspring:
type: array
items:
$ref: "#/schemas/animal"
required:
- name
- offspring
```
Currently, it renders an example based on `S` as follows
```
{
"name":"John Doe",
"pets":[{
"name":"Bob the cat","
offspring":[{
"name":"Bob the cat",
"offspring":[{
"name":"Bob the cat", …
```

Improve rendering of schemas with circular references

---

bundler/composer_functions.go
bundler/composer_functions_test.go

Fixes #421 
Refs with dots were failing. Fixes that behavior, while preserving the ability to actually strip the filename

Fix Bundler Compose Mode Breaking with Non Filename Dots

---

what-changed/model/operation.go
what-changed/model/operation_test.go

I ran into this bug: https://github.com/pb33f/openapi-changes/issues/209 And tried to fix it. It seems like the breaking argument was hard coded to true rather than checking the required field on the parameter.

Check required field on added parameters

---

what-changed/model/parameter.go
what-changed/model/parameter_test.go

Just from looking at the changed parameter result array  coming from https://github.com/pb33f/libopenapi/blob/8fd18648b47e4a823edab8680e14e89feb897290/what-changed/model/operation.go#L337-L342 it's hard to understand what parameters have actually changed.
_I'm not sure if this is the way you want the model to change going forward, but having the parameter name value somewhere helps when inspecting the changes._

Embed name of the changed parameter

---

what-changed/model/parameter.go
what-changed/model/parameter_test.go

When parameter is changed from `required: true` to `required: false` it's considered _breaking_. I would expect this to be _non_-breaking.

Use right side required value to consider it breaking or not

---

what-changed/model/path_item.go
what-changed/model/path_item_test.go

Check required field on added endpoint level parameters

---

document_test.go
index/resolver.go
test_specs/recursive-expression-test.yaml

Fixes https://github.com/pb33f/libopenapi/issues/439

Skip anyOf/allOf/oneOf in properties

---

bundler/bundler.go
bundler/bundler_composer.go
bundler/bundler_composer_test.go

Composed Bundling Changes
- Updates refs in discriminator mappings under composed bundling
fixes #433

Fix Discriminator with Composed Bundling

---

bundler/bundler_test.go
datamodel/high/v3/document_test.go
index/rolodex_file_loader.go
index/spec_index_test.go
renderer/schema_renderer.go
renderer/schema_renderer_test.go

The PR refactors tests with [`t.TempDir`](https://pkg.go.dev/testing#T.TempDir):
> TempDir returns a temporary directory for the test to use. The directory is automatically removed when the test and all its subtests complete. Each subsequent call to t.TempDir returns a unique directory; if the directory creation fails, TempDir terminates the test by calling Fatal.
Additionally, this PR fixes an issue where a file was not being closed.

refactor: simplify tests with t.TempDir; close file handler
